CREATE DATABASE IF NOT EXISTS Teachers;
USE Teachers;

DROP TABLE IF EXISTS Subjects;
DROP TABLE IF EXISTS Teacher;

CREATE TABLE Subjects (
    MaMH INT PRIMARY KEY,
    TenMH NVARCHAR(100) NOT NULL,
    SoTinChi INT CHECK (SoTinChi > 0)
);

CREATE TABLE Teacher (
    MaGV INT PRIMARY KEY,
    HoTenGV NVARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE
);
 
ALTER TABLE Subjects
ADD MaGV INT;

ALTER TABLE Subjects
ADD CONSTRAINT FK_Subjects_Teacher
FOREIGN KEY (MaGV)
REFERENCES Teacher(MaGV);
